# Generated by Django 4.0.4 on 2022-06-06 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField(verbose_name='Комната')),
                ('room_bool', models.BooleanField(default=True, verbose_name='Релевантность')),
                ('category', models.CharField(max_length=150, verbose_name='Категория')),
                ('price', models.IntegerField(null=True, verbose_name='Цена (сум)')),
            ],
            options={
                'verbose_name': 'Комнату',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('pasport_serial_num', models.CharField(help_text='*AB-0123456', max_length=100, verbose_name='Серия паспорта')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('img', models.FileField(help_text='Загружайте файл в формате .pdf', upload_to='PDF img', verbose_name='Фото документа')),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата прибытия')),
                ('leave_date', models.DateField(blank=True, default='После ухода!', null=True, verbose_name='Дата отбытия')),
                ('guest_count', models.IntegerField(default=1, verbose_name='Кол-во людей')),
                ('room_bool', models.BooleanField(default=False, help_text='При бронирование отключите галочку', verbose_name='Релевантность')),
                ('price', models.IntegerField(null=True, verbose_name='Цена (сум)')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('rooms', models.ForeignKey(help_text='Номер в который хотите заселить гостя!', limit_choices_to={'room_bool': True}, on_delete=django.db.models.deletion.CASCADE, related_name='reg', to='reg_admin.rooms', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Регистрация',
            },
        ),
    ]
