# Generated by Django 4.0.4 on 2022-06-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='pay_type',
            field=models.CharField(choices=[('Site', 'Сайт'), ('Bot', 'Бот'), ('Reseption', 'Ресепшен')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
