# Generated by Django 4.0.4 on 2022-08-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_admin', '0002_registration_pay_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='registration',
            name='tel_num',
            field=models.CharField(default=1, max_length=12, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='pay_type',
            field=models.CharField(choices=[('Site', 'Сайт'), ('Bot', 'Бот'), ('Reseption', 'Ресепшен')], max_length=15, verbose_name='Платеж произведен'),
        ),
    ]
