# Generated by Django 4.0.4 on 2022-05-18 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ralevant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool_roo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField()),
                ('category', models.CharField(max_length=150)),
                ('room_bool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name1', to='reg_admin.ralevant')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('pasport_serial_num', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('img', models.FileField(upload_to='')),
                ('visit_date', models.DateTimeField()),
                ('leave_date', models.DateTimeField()),
                ('guest_count', models.IntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room_bool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name2', to='reg_admin.ralevant')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_admin.rooms')),
            ],
        ),
    ]
