# Generated by Django 3.2.13 on 2022-05-27 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='leave_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отбытия'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='visit_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 27, 0, 0), verbose_name='Дата прибытия'),
        ),
    ]
