# Generated by Django 3.2.13 on 2022-05-27 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_admin', '0002_auto_20220527_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 13, 11), verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.CharField(max_length=105),
        ),
    ]
