# Generated by Django 3.2.13 on 2022-05-27 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reg_admin', '0002_auto_20220527_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='leave_date',
            field=models.DateField(blank=True, default='После ухода!', null=True, verbose_name='Дата отбытия'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена (сум)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена (сум)'),
        ),
    ]
