# Generated by Django 3.2.13 on 2022-05-30 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reg_admin', '0003_auto_20220527_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Администратор'),
        ),
    ]
