# Generated by Django 3.2.13 on 2022-05-27 08:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_admin', '0003_auto_20220527_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=105, verbose_name='Цена')),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 13, 28), verbose_name='Дата прибытия'),
        ),
        migrations.AddField(
            model_name='registration',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reg_admin.price', verbose_name='Price1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_admin.price', verbose_name='Price'),
        ),
    ]
