# Generated by Django 3.2.13 on 2022-05-27 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_admin', '0004_auto_20220527_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 13, 29), verbose_name='Дата прибытия'),
        ),
    ]
