# Generated by Django 3.2.13 on 2022-05-30 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reg_admin', '0004_alter_registration_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Администратор'),
            preserve_default=False,
        ),
    ]
