# Generated by Django 3.2.13 on 2022-05-27 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_admin', '0007_auto_20220527_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='price',
            field=models.CharField(default=1, max_length=105),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 14, 11), verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.CharField(max_length=105, verbose_name='Цена (сум)'),
        ),
    ]
