# Generated by Django 4.0.4 on 2022-06-11 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('President Lux', 'President Lux'), ('Lux', 'Lux'), ('Double', 'Double'), ('Standard', 'Standard')], max_length=150, verbose_name='Категория')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('bron_slug', models.SlugField(null=True, verbose_name='Cлаг для заказа')),
                ('room_num', models.CharField(max_length=250, verbose_name='Номер')),
                ('about_en', models.TextField(null=True, verbose_name='Подробности English')),
                ('about_ru', models.TextField(null=True, verbose_name='Подробности на Русском')),
                ('about_uz', models.TextField(null=True, verbose_name="Подробности O'zbekcha")),
                ('about_payments_ru', models.TextField(default='После успешной оплаты средств вам предаставят чек (QR-CODE)\n\nСохраните ее для подтверждения во время прихода в "Hotel Uzbegim"', verbose_name='Подробности во время платежа')),
                ('about_payments_en', models.TextField(default='After successful payment of funds, you will be provided with a receipt (QR-CODE)\n\nKeep it for confirmation when you arrive at "Hotel Uzbegim"', verbose_name='Подробности во время платежа')),
                ('about_payments_uz', models.TextField(default="Mablag'ni muvaffaqiyatli to'laganingizdan so'ng sizga chek (QR-CODE) beriladi\n\n“Uzbegim” mehmonxonasiga kelganingizda uni tasdiqlash uchun saqlang", verbose_name='Подробности во время платежа')),
                ('price_ru', models.CharField(max_length=150, verbose_name='Цена ₽')),
                ('price_en', models.CharField(max_length=150, verbose_name='Цена $')),
                ('price_uz', models.CharField(max_length=150, verbose_name='Цена')),
                ('price_payments_uzs', models.IntegerField(verbose_name='Цена для платежа')),
                ('price_payments_usd', models.IntegerField(verbose_name='Цена для платежа $')),
                ('price_payments_rub', models.IntegerField(verbose_name='Цена для платежа ₽')),
                ('logo', models.URLField(verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Категорий',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Successful_pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField()),
                ('room_category', models.CharField(max_length=150, null=True)),
                ('price', models.BigIntegerField()),
                ('currency', models.CharField(max_length=50)),
                ('provider_payment_charge_id', models.TextField()),
                ('qr_link', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('tel_num', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('name', models.TextField()),
                ('visit_date', models.DateTimeField()),
                ('leav_date', models.DateTimeField()),
                ('day_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True)),
                ('nickname', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя')),
                ('username', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя пользователя')),
                ('lang', models.CharField(default='ru', max_length=10, null=True, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Пользователя',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(verbose_name='Фотография')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_bot.category', verbose_name='img1')),
            ],
        ),
    ]
