# Generated by Django 4.0.4 on 2022-06-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_bot', '0003_alter_user_options_alter_user_nickname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('President Lux', 'President Lux'), ('Lux', 'Lux'), ('Double', 'Double'), ('Standard', 'Standard')], max_length=150, verbose_name='Категория')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('img', models.FileField(upload_to='Room .img', verbose_name='Фотография')),
                ('room_num', models.IntegerField(verbose_name='Номер')),
                ('about', models.TextField(verbose_name='Подробности')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
