# Generated by Django 4.0.4 on 2022-06-02 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_bot', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='Room .img', verbose_name='Фотография')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_bot.category', verbose_name='img1')),
            ],
        ),
    ]
