# Generated by Django 4.0.4 on 2022-06-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_bot', '0006_remove_category_about_remove_category_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='about',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
        migrations.RemoveField(
            model_name='image',
            name='price',
        ),
        migrations.RemoveField(
            model_name='image',
            name='room_num',
        ),
        migrations.AddField(
            model_name='category',
            name='about',
            field=models.TextField(default=1, verbose_name='Подробности'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.FileField(default=1, upload_to='Room .img', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='room_num',
            field=models.IntegerField(default=1, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
