# Generated by Django 4.0.4 on 2022-06-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_bot', '0007_remove_image_about_remove_image_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.FileField(default=1, upload_to='Room .img', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
