# Generated by Django 4.0.4 on 2022-06-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_bot', '0009_alter_category_room_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорий', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.URLField(verbose_name='Фотография'),
        ),
    ]
