# Generated by Django 4.0.4 on 2022-06-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_bot', '0010_alter_category_options_alter_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
