# Generated by Django 4.0.4 on 2022-06-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_bot', '0011_alter_user_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bron_slug',
            field=models.SlugField(null=True, verbose_name='Cлаг для заказа'),
        ),
    ]
