# Generated by Django 4.0.4 on 2022-06-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_bot', '0013_category_price_paymetns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='price',
            field=models.CharField(max_length=150, verbose_name='Цена'),
        ),
    ]
