# Generated by Django 4.0.4 on 2022-06-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_bot', '0014_alter_category_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.URLField(default=1, verbose_name='Логотип'),
            preserve_default=False,
        ),
    ]
