# Generated by Django 4.0.4 on 2022-06-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_bot', '0015_category_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='about_payments',
            field=models.TextField(default='После успешной оплаты средств вам предаставят чек (QR-CODE)\n\nСохраните ее для подтверждения во время прихода в "Hotel Uzbegim"', verbose_name='Подробности во время платежа'),
        ),
    ]
