# Generated by Django 4.0.4 on 2022-06-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_bot', '0016_category_about_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(default='ru', max_length=10),
        ),
    ]
