# Generated by Django 4.0.4 on 2022-06-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_bot', '0017_user_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.CharField(default='ru', max_length=10, null=True, verbose_name='Язык'),
        ),
    ]
