# Generated by Django 4.0.4 on 2022-06-06 13:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_category', models.CharField(choices=[('standard', 'Standard'), ('double', 'Double'), ('lux', 'Lux'), ('president lux', 'President Lux')], max_length=50, verbose_name='Категория')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('tel_num', models.IntegerField(verbose_name='Номер телефона')),
                ('tel_num2', models.IntegerField(blank=True, null=True, verbose_name='Номер телефона (2)')),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата прибытия')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='Дата отбытия')),
                ('email', models.EmailField(max_length=254)),
                ('guest_count', models.IntegerField(default=1, verbose_name='Кол-во людей')),
            ],
            options={
                'verbose_name': 'Номер (Reg)',
                'verbose_name_plural': 'Номера (Reg)',
            },
        ),
        migrations.CreateModel(
            name='UserRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('President Lux', 'President Lux'), ('Lux', 'Lux'), ('Double', 'Double'), ('Standard', 'Standard')], max_length=150, verbose_name='Категория')),
                ('room_num', models.CharField(max_length=150)),
                ('about', models.TextField(verbose_name='Подробности')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Номер (About)',
                'verbose_name_plural': 'Номера (About)',
            },
        ),
        migrations.CreateModel(
            name='UserImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='User img', verbose_name='Фотография')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_user.userroom', verbose_name='img2')),
            ],
            options={
                'verbose_name': 'Фотографию',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
