# Generated by Django 4.0.4 on 2022-06-01 11:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reg_admin', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('tel_num', models.IntegerField(verbose_name='Номер телефона')),
                ('tel_num2', models.IntegerField(blank=True, null=True, verbose_name='Номер телефона (2)')),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата прибытия')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='Дата отбытия')),
                ('email', models.EmailField(max_length=254)),
                ('guest_count', models.IntegerField(default=1, verbose_name='Кол-во людей')),
                ('rooms', models.ForeignKey(help_text='Номер в который хотите заселить гостя!', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='reg_admin.rooms', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Номер пользователя',
                'verbose_name_plural': 'Комнаты Пользователей',
            },
        ),
    ]
