# Generated by Django 4.0.4 on 2022-06-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='tel_num',
            field=models.BigIntegerField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='tel_num2',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Номер телефона (2)'),
        ),
    ]
