# Generated by Django 4.0.4 on 2022-06-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='rooms',
        ),
        migrations.AddField(
            model_name='userreg',
            name='room_category',
            field=models.CharField(choices=[('standard', 'Standard'), ('double', 'Double'), ('lux', 'Lux'), ('president lux', 'President Lux')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
