# Generated by Django 4.0.4 on 2022-06-03 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('President Lux', 'President Lux'), ('Lux', 'Lux'), ('Double', 'Double'), ('Standard', 'Standard')], max_length=150, verbose_name='Категория')),
                ('room_num', models.CharField(max_length=150)),
                ('about', models.TextField(verbose_name='Подробности')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.AlterModelOptions(
            name='userreg',
            options={'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.CreateModel(
            name='UserImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='User img', verbose_name='Фотография')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_user.userroom', verbose_name='img2')),
            ],
        ),
    ]
