# Generated by Django 4.0.4 on 2022-08-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_user', '0002_alter_userreg_tel_num_alter_userreg_tel_num2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroom',
            name='img360',
            field=models.FileField(default=1, upload_to='', verbose_name='Фотография в 360'),
            preserve_default=False,
        ),
    ]
