# Generated by Django 4.0.4 on 2022-08-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_user', '0003_userroom_img360'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimg',
            name='name',
        ),
        migrations.AddField(
            model_name='userroom',
            name='img',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='img2', to='reg_user.userimg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userroom',
            name='room_num',
            field=models.CharField(max_length=150, verbose_name='Доступные номера для категории'),
        ),
    ]
