# Generated by Django 4.0.4 on 2022-08-09 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_user', '0004_remove_userimg_name_userroom_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroom',
            name='img',
        ),
        migrations.AddField(
            model_name='userimg',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reg_user.userroom', verbose_name='img2'),
            preserve_default=False,
        ),
    ]
