# Generated by Django 4.0.4 on 2022-08-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_user', '0005_remove_userroom_img_userimg_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroom',
            name='title_img',
            field=models.FileField(default=1, upload_to='Фотография комнат/title_img/', verbose_name='Фотография основной панели'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userimg',
            name='img',
            field=models.FileField(upload_to='Фотография комнат', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='userimg',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userimg_set', to='reg_user.userroom'),
        ),
        migrations.AlterField(
            model_name='userroom',
            name='img360',
            field=models.FileField(upload_to='Фотография комнат/img360/', verbose_name='Фотография в 360'),
        ),
    ]
